name: dbc
channels:
  - defaults
dependencies:
  - pip
  - python=3.7
  - pytorch
  - torchvision
  - cudatoolkit=10.2
  - absl-py
  - pyparsing
  - pip:
    - termcolor
    - opencv-python
    - pillow==6.1
    - scikit-image
    - scikit-video
    - tb-nightly
    - tqdm
    - imageio
    - imageio-ffmpeg
    - pygame
    - networkx
    - dotmap
